site_name: One-KVM 文档
site_description: One-KVM，基于 PiKVM 的开源 IP KVM 项目。
site_author: SilentWind
site_url: https://one-kvm.mofeng.run/

docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - navigation.expand
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      

repo_url: https://github.com/mofeng-git/One-KVM
repo_name: mofeng-git/One-KVM

copyright: Copyright &copy; 2023 - 2024 SilentWind

extra_javascript:
    - 'js/baidu-tongji.js'


plugins:
  - search:
      lang: zh
  - mkdocs-video:
      video_controls: True
      video_autoplay: false
      is_video: True
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Asia/Shanghai
      type: date
      locale: zh
  - glightbox
    

nav:
    - "开始":
      - "介绍": index.md
      - "写在前面": prepare.md
      - "Docker 部署": start_install/docker_install.md
      - "已适配硬件安装":
        - "玩客云": start_install/onecloud_install.md
        #- "X86 主机安装": x86_install.md
        - "私家云二代": start_install/cumebox2_install.md
        - "香橙派 Zero": start_install/orangepizero_install.md
        - "S905l3a 盒子": start_install/s905l3a_install.md
        - "虚拟机部署": start_install/virtualmachine_install.md
        - "群晖 NAS": start_install/synology_install.md
        - "我家云盒子": start_install/chainedbox_install.md
        - "章鱼星球": start_install/octopus-flanet_install.md
        - "章鱼星球（安卓-硬件编码）": start_install/octopus-flanet_andriod_install.md
        - "龙芯久久派": start_install/2k0300_install.md
        #- "玩客云套装（停止维护）": start_install/onecloud_guide.md
      - "常见问题": start_install/faq.md
      - "感谢": thanks.md

    - "网络":
      - "互联网访问":
        - "端口转发": network/port_forwarding.md
        - "Frp 端口映射": network/frp.md
        - "Tailscale 异地组网": network/tailscale.md
        - "Cloudflared 隧道": network/cloudflared.md
      #- "WIFI 连接": network/wifi.md
      - "SSL 加密连接": network/ssl.md

    - "音视频":
      - "H.264 / WebRTC": audio_and_video/h264.md
      - "H.264 音频": audio_and_video/audio.md
      - "视频录制": audio_and_video/video_record.md

    - "外围设备":
      - "键盘和鼠标":
        - "鼠标模式": attached_device/mouse.md
        - "鼠标抖动器": attached_device/mouse_jiggler.md
        - "CH9329 HID": attached_device/ch9329_hid.md
        # "蓝牙 HID": attached_device/bluetooth_hid.md
      - "大容量存储驱动器": attached_device/msd.md
      - "USB 以太网": attached_device/usb_ethernet.md
      - "USB 串口": attached_device/usb_serial.md
      - "动态 USB 配置": attached_device/usb_dynamic.md
      - "ATX 电源控制":
        - "玩客云 GPIO": attached_device/onecloud_atx.md
        #- "GPIO 通用配置": attached_device/gpio.md
        - "USB 继电器": attached_device/usb_relay.md
        #- "USB 转 GPIO 配置": attached_device/usb2gpio.md

    - "高级用法":
      #- "启动时配置": advanced_using/on_start_config.md
      - "外观主题": advanced_using/appearances.md
      - "VNC 连接": advanced_using/vnc.md
      - "KVM 一控多": advanced_using/kvm_switch.md
      - "WOL 网络唤醒": advanced_using/wol.md
      - "Webterm 网页终端": advanced_using/webterm.md
      #- "身份认证": auth.md
      - "2FA 双重身份验证": advanced_using/2fa.md
      #- "IPMI 和 Redfish 集成": advanced_using/ipmi.md
      #- "HDMI 环出": advanced_using/loop_out.md

    - "周边套件与开发":
      - "周边套件": development/parts_library.md
      - "HTTP API": development/api.md
      - "构建 One-KVM 系统": development/building_os.md
      - "知识库": development/develop.md
