site_name: One-KVM 文档
site_description: One-KVM，基于 PiKVM 的开源 IP KVM 项目。
site_author: SilentWind
site_url: https://one-kvm.mofeng.run/

docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      

repo_url: https://github.com/mofeng-git/One-KVM
repo_name: mofeng-git/One-KVM

copyright: Copyright &copy; 2023 - 2024 SilentWind

extra_javascript:
    - 'js/baidu-tongji.js'


plugins:
  - search:
      lang: zh
  - mkdocs-video:
      video_controls: True
      video_autoplay: false
      is_video: True
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Asia/Shanghai
      type: date
      locale: zh
  - glightbox
    

nav:
    - "开始":
      - "介绍": index.md
      - "写在前面": prepare.md
      - "软件安装":
        - "Docker 部署（推荐）": docker_install.md
        - "玩客云": onecloud_install.md
        #- "X86 主机安装": x86_install.md
        - "私家云二代": cumebox2_install.md
        #- "群晖 NAS": synology_install.md
        #- "龙芯久久派": 2k0300_install.md
        #- "s905l3a 盒子": s905l3a_install.md
        #- "我家云盒子": chainedbox_install.md
        #- "虚拟机部署": virtualmachine_install.md
        #- "玩客云套装（停止维护）": onecloud_guide.md
      #- "身份认证": auth.md
      - "常见问题": faq.md

    - "网络":
      - "互联网访问":
        - "端口转发": port_forwarding.md
        - "Frp 端口映射": frp.md
        - "Tailscale 异地组网": tailscale.md
        - "Cloudflared 隧道": cloudflared.md
      #- "WIFI 连接": wifi.md
      - "SSL 加密连接": ssl.md

    - "音视频":
      - "H.264 / WebRTC": h264.md
      - "H.264 音频": audio.md
      - "视频录制": video_record.md

    - "外围设备":
      - "键盘和鼠标":
        - "鼠标模式": mouse.md
        - "鼠标抖动器": mouse_jiggler.md
        - "CH9329 HID": ch9329_hid.md
        # "蓝牙 HID": bluetooth_hid.md
      - "大容量存储驱动器": msd.md
      - "USB 以太网": usb_ethernet.md
      - "USB 串口": usb_serial.md
      - "动态 USB 配置": usb_dynamic.md
      - "ATX 电源控制":
        - "玩客云 GPIO": onecloud_atx.md
        #- "GPIO 通用配置": gpio.md
        - "USB 继电器": usb_relay.md
        #- "USB 转 GPIO 配置": usb2gpio.md

    - "高级用法":
      #- "启动时配置": on_start_config.md
      - "VNC 连接": vnc.md
      - "KVM 一控多": kvm_switch.md
      - "WOL 网络唤醒": wol.md
      - "Webterm 网页终端": webterm.md
      - "2FA 双重身份验证": 2fa.md
      #- "IPMI 和 Redfish 集成": ipmi.md
      #- "HDMI 环出": loop_out.md

    - "开发":
      - "HTTP API": api.md
      - "构建 One-KVM 系统": building_os.md
      - "周边套件": parts_library.md
      - "知识库": develop.md

    - "感谢": thanks.md
