site_name: One-KVM文档
site_description: One-KVM，基于PiKVM的开源IP KVM项目。
site_author: SilentWind
site_url: https://one-kvm.mofeng.run/

docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.expand
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences

repo_url: https://github.com/mofeng-git/One-KVM
repo_name: mofeng-git/One-KVM

copyright: Copyright &copy; 2023 - 2024 SilentWind

extra_javascript:
    - 'js/baidu-tongji.js'

nav:
    - "介绍": index.md
    - "设备指南":
        - "玩客云套装": onecloud_guide.md
        - "玩客云 DIY 安装": onecloud_install.md
        - "X86 主机安装": x86_install.md
        - "Docker 安装": docker_install.md
    - "快速开始": first_steps.md
    - "功能对比": compare.md
    - "MSD 虚拟存储驱动器": msd.md
    - "VNC 连接": vnc.md
    - "WOL 网络唤醒": wol.md
    - "Webterm 网页终端": webterm.md
    - "2FA 双重身份验证": 2fa.md
    - "H.264 视频": h264.md
    - "KVM 一控多": onecloud_kvm.md
    - "ATX 电源控制": onecloud_atx.md
    - "HDMI 环出": loop_out.md
    - "开发知识库": develop.md
    - "常见问题": faq.md
    - "感谢": thanks.md
